esphome:
  name: temp_living_room
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: !secret ssid
  password: !secret wifi_password
    # Optional manual IP
  manual_ip:
    static_ip: 192.168.2.201
    gateway: 192.168.2.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "LivingRoom Temp Fallback Hotspot"
    password: "RxcmiuCeoF75"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "password"

ota:
  password: "password"

i2c: 
  sda: D2 
  scl: D1

sensor:
  - platform: bme280
    temperature:
      name: "Living Room Temperature"
      oversampling: 16x
    pressure:
      name: "Living Room Pressure"
    humidity:
      name: "Living Room Humidity"
    address: 0x76
    #then:
      #- deep_sleep.enter: deep_sleep_1
    update_interval: 30s
deep_sleep:
  run_duration: 1min
  sleep_duration: 10min